language: generic
services:
  - docker

notifications:
  email:
    on_success: change
    on_failure: always
env:
  global:
    - CATKIN_LINT=pedantic
    - PYLINT_ARGS="--output-format=parseable --errors-only"
    - PYLINT2_CHECK=true
    - PYLINT3_CHECK=true
env:
  matrix:
    - ROS_DISTRO=kinetic ROS_REPO=ros
    - ROS_DISTRO=kinetic ROS_REPO=ros-shadow-fixed
    - ROS_DISTRO=melodic ROS_REPO=ros
    - ROS_DISTRO=melodic ROS_REPO=ros-shadow-fixed
install:
  - git clone --quiet --depth 1 https://github.com/fmessmer/industrial_ci.git .industrial_ci -b master_pylint
script:
  - .industrial_ci/travis.sh